plugins {
    id 'com.gradleup.shadow'
}

repositories {
    flatDir {
        dirs '../libs'
    }
}

dependencies {
    implementation project(':common')
    compileOnly 'com.velocitypowered:velocity-api:3.3.0-SNAPSHOT'
    annotationProcessor 'com.velocitypowered:velocity-api:3.3.0-SNAPSHOT'
    compileOnly name: 'limboapi-1.1.27-SNAPSHOT'
}

processResources {
    filteringCharset = 'UTF-8'
    inputs.property('version', project.version)
    filesMatching('velocity-plugin.json') {
        filter { line -> line.replace('${project.version}', project.version) }
    }
}

shadowJar {
    archiveBaseName.set('SimpleLogin-Velocity')
    archiveClassifier.set('')
    archiveVersion.set(project.version)

    exclude 'com.google.code.gson:**'

    relocate 'com.zaxxer.hikari', 'com.premiumauth.simplelogin.libs.hikari'
    relocate 'okhttp3', 'com.premiumauth.simplelogin.libs.okhttp3'
    relocate 'okio', 'com.premiumauth.simplelogin.libs.okio'
    relocate 'com.github.benmanes.caffeine', 'com.premiumauth.simplelogin.libs.caffeine'
}

build.dependsOn shadowJar

jar {
    enabled = false
}
